apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rsf2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ojdn-tenant/rhtap-demo-app/hacbs-test-project-rsf2@sha256:28bf3e0a97c4205060ac5372b1afb21f6d9ea39570f151c2932af6abd81ea3a5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
