apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-rsf2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ojdn-tenant/rhtap-demo-app/hacbs-test-project-rsf2@sha256:8f4665509452a0e3213b42c3fd977999f8e72f467068fe4e19b9ac972eec92a5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
